# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem 'mini-smtp-server'
gem 'mail'
gem 'pony'
gem 'daemons'
#gem "tlsmail"
#
require 'net/smtp'
#require 'deamons'
#require 'mail'
#require 'tempfile'
